### PR TITLE
Add a new option to exclude source files from being processed by Margina...

### PR DESCRIPTION
**Pull request by fgiasson**
...lia.

The new option is available at the command line with "-e" or "--exclude". It can also be part of the project.clj file via the ":exclude" keyword.

I was requiring this feature because I often have local testing files which I don't want to be included in the documentation.

The new option is quite simple: it simply filter out the files that have been identified by the option out of the "sources" var before it is being used by multidoc! or uberdoc!

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Hi, sorry to see that this pull has languished for three weeks now.

I pulled down your branch and local tests fail to run - however, it seems unrelated to your changes.  How do you propose that these changes be validated?  If feasible, please add a test.

**Comment by fgiasson** [comment]
Hi @benjamin-bader,

Thanks for looking into this. I am unto something else, but I should be able to look into this tomorrow. Will keep you updated.

**Comment by fgiasson** [comment]
I just fetched the latest changes that were commited since I made this pull request.

I have a few ideas to create a test for the new feature.

However, even after commenting all the code I changed, I cannot have the tests run with `lein test`.

I am always seeing an error around:

```
        at marginalia.core$find_processable_file_paths.invoke(core.clj:92)
        at marginalia.test.helpers$find_clojure_file_paths.invoke(helpers.clj:20)
        at marginalia.test.uberdoc$eval1087$fn__1088.invoke(uberdoc.clj:9)
        at marginalia.test.uberdoc$eval1087.invoke(uberdoc.clj:6)
```

where it complains about the execution of the regex in:

```
(defn find-processable-file-paths
  "Returns a seq of processable file paths (strings) in alphabetical order by
  namespace."
  [dir pred]
  (->> (io/file dir)
       (file-seq)
       (filter (partial processable-file? pred))
       (sort-by #(->> % parse-ns second))
       (map #(.getCanonicalPath %))))
```

(what is being passed to `sort-by`)

Am I the only one experiencing this issue (still)?

**Comment by benjamin-bader** [comment]
No, you aren't the only one.  The tests are broken as-is, and the feature looks good to me.  Merged.

**Comment by fgiasson** [comment]
Great thanks!

**Pull request merged**
