### PR TITLE
handle (ignore) extra args from LispReader

### LINKED ISSUE #153: Marginalia appears to break with Clojure 1.7.0
I'm guessing because of use of LispReader internals, though I haven't dug that deep yet. Possibly see https://github.com/Engelberg/instaparse/pull/94 http://dev.clojure.org/jira/browse/CLJ-1424

### PR DESCRIPTION
**Pull request by MichaelBlume**
with the new reader conditionals patch, readers are passed additional
arguments.

Ignore them.

Fixes #153

### CODE REVIEW

**Comment by MichaelBlume** [comment]
This makes my project build anyway -- if there's something more involved that needs to be done with these args, please let me know.

**Comment by MichaelBlume** [comment]
ping

**Comment by gekkoe** [comment]
Is marginalia no longer being maintained?

**Comment by eigenhombre** [comment]
This also fixed my project.

**Comment by MichaelBlume** [comment]
@gekkoe it really looks that way? I'm not sure what to do.

**Comment by benjamin-bader** [comment]
Hi.  @gdeer81 gave me commit access some time ago when I sent in a few pull requests, but I haven't heard from him at all in over a year.  I'm not an admin, unfortunately.

I have neither the time nor the interest for taking over maintenance.  I can merge this request, but going forward forking seems like the best strategy.

**Comment by MichaelBlume** [comment]
I have published a fork with the fix: https://clojars.org/michaelblume/marginalia

**Pull request merged**
